### ISSUE TITLE
[BUG REPORT] - 4cget it no work

### ISSUE THREAD

**Issue by sela-dore** [SegoCode/4cget#3]
### Description

not working anymore sad face

![image](https://github.com/user-attachments/assets/4e015063-181e-4069-93be-e88b7376ff2d)

### Steps to reproduce

1. do exactly as i did about a month ago ... go run 4cget.go https://boards.4chan.org/...
2. it looks like its working
3. it successfully downloads 0 files in xxx ms
4. be sad no images

### Expected behavior

i expected to download a lot of alice images

### Actual behavior

i did no get any alice images 

### OS version

Windows 10

### Confirmation

- [X] I performed a [search of the issue tracker](https://github.com/SegoCode/4cget/issues) to avoid opening a duplicate issue
- [X] I understand that not filling out this template correctly may lead to the issue being closed

**Comment by SegoCode** [comment]
Please, download the latest version https://github.com/SegoCode/4cget/releases/tag/1.6

**Comment by sela-dore** [comment]
![image](https://github.com/user-attachments/assets/97854074-aef9-43a7-999d-c5733185fa82)
that was it !
ty for your effort and for letting a fool like me use your thing its great !
